on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32rom

jobs:
  fox32rom-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: nix build .#fox32rom

      - name: Upload fox32.rom
        uses: actions/upload-artifact@v2
        with:
          name: fox32.rom
          path: result/bin/fox32.rom

      - name: Upload fox32rom.def
        uses: actions/upload-artifact@v2
        with:
          name: fox32rom.def
          path: result/dev/fox32rom.def
